force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Return Money</fullName>
            </value>
            <value>
                <fullName>Resend items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApproveReturnItemController.cls
public with sharing class ApproveReturnItemController {
    @AuraEnabled
    public static void CreateApprovalRequest(String comment, String strategy, Id recordId) {
        Return_Item__c item = new Return_Item__c(Id = recordId, Strategy__c = strategy);
        update item;

        Id caseOwner = [
            SELECT OwnerId
            FROM Case
            WHERE Id IN (SELECT Case__c FROM Return_Item__c WHERE Id = :recordId)
        ][0]
        .OwnerId;

        Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
        request.setComments(comment);
        request.setObjectId(recordId);
        request.setNextApproverIds(new List<Id>{ caseOwner });
        request.setProcessDefinitionNameOrId('Return_Item_Approval');
        request.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(request);
    }
}