force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Synchronized__c.field-meta.xml
<CustomField>
    <fullName>Synchronized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synchronized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/ReturnItemTriggerHandler.cls
public class ReturnItemTriggerHandler extends TriggerHandler {
    public override void beforeUpdate() {
        //check if item is external and if it is prevent its update
    }

    public override void afterUpdate() {
        for (Return_Item__c returnItem : (List<Return_Item__c>) Trigger.new) {
            if (returnItem.Synchronized__c == false) {
                continue;
            }

            if (
                returnItem.Status__c == 'Pending' ||
                returnItem.Status__c == ((Return_Item__c) Trigger.oldMap.get(returnItem.Id)).Status__c
            ) {
                continue;
            }

            System.enqueueJob(new ReturnItemSyncQueueable(returnItem));
        }
    }
}