force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <label>Case External Id</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <label>Product External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Returned_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Returned_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Returned Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Return Money</fullName>
            </value>
            <value>
                <fullName>Resend items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/testdata/objectbuilders/ReturnItemBuilder.cls
public class ReturnItemBuilder {
    public Return_Item__c returnItem = new Return_Item__c();

    public ReturnItemBuilder setQuantity(Integer quantity) {
        returnItem.Returned_Quantity__c = quantity;
        return this;
    }

    public ReturnItemBuilder setOrderProduct(OrderItem relatedOrderItem) {
        returnItem.Order_Product__c = relatedOrderItem.Id;
        return this;
    }

    public ReturnItemBuilder setStatus(String status) {
        returnItem.Status__c = status;
        return this;
    }

    public ReturnItemBuilder setStrategy(String strategy) {
        returnItem.Strategy__c = strategy;
        return this;
    }

    public ReturnItemBuilder setCaseExternalId(String externalId) {
        returnItem.Case_External_Id__c = externalId;
        return this;
    }

    public ReturnItemBuilder setExternalId(String externalId) {
        returnItem.External_Id__c = externalId;
        return this;
    }

    public ReturnItemBuilder setProductExternalId(String productExternalId) {
        returnItem.Product_External_Id__c = productExternalId;
        return this;
    }
}