force-app/main/default/objects/Case/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Case External Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_case_items__e/External_case_items__e.object-meta.xml
<CustomObject>
    <label>External case items</label>
    <pluralLabel>External cases items</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_case_items__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <label>Case External Id</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <label>Product External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Returned_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Returned_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Returned Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/returns/ReturnOrdersController.cls
public with sharing class ReturnOrdersController {
    @AuraEnabled(cacheable=true)
    public static List<OrderItem> getOrderItemsForOrder(Id orderId) {
        return [
            SELECT Product2.Name, Product2.External__c, Product2.ProductExternalId__c, Quantity
            FROM OrderItem
            WHERE OrderId = :orderId
        ];
    }

    @AuraEnabled
    public static Map<String, String> createCase(String status, String subject, String description) {
        String externalCaseId = UUID.randomUUID().toString();
        Case caseToCreate = new Case(Subject = subject, Description = description, Status = status, Case_External_Id__c = externalCaseId);
        insert caseToCreate;

        Map<String, String> resultMap = new Map<String, String>();
        resultMap.put('caseId', caseToCreate.Id);
        resultMap.put('caseExternalId', externalCaseId);

        return resultMap;
    }

    @AuraEnabled
    public static List<Return_Item__c> insertJunctionObjects(List<Return_Item__c> itemsToInsert) {
        for (Return_Item__c item : itemsToInsert) {
            item.External_Id__c = UUID.randomUUID().toString();
        }

        insert itemsToInsert;
        return itemsToInsert;
    }

    @AuraEnabled
    public static List<Return_Item__c> filterExternalItems(List<Return_Item__c> initialItems) {
        Set<Id> itemIds = new Set<Id>();

        for (Return_Item__c item : initialItems) {
            itemIds.add(item.Id);
        }

        List<Return_Item__c> externalItems = [
            SELECT External_Id__c, Case_External_Id__c, Returned_Quantity__c, Order_Product__r.Product2.ProductExternalId__c
            FROM Return_Item__c
            WHERE Id IN :itemIds AND Order_Product__r.Product2.External__c = TRUE
        ];

        for (Return_Item__c item : externalItems) {
            item.Product_External_Id__c = item.Order_Product__r.Product2.ProductExternalId__c;
        }

        return externalItems;
    }

    @AuraEnabled
    public static void sendExternalItems(List<Return_Item__c> itemsToSend, String caseExternalId) {
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint('callout:SynchronizeProducts/services/data/v61.0/sobjects/External_case_items__e');

        External_case_items__e platformEvent = new External_case_items__e(
            Payload__c = JSON.serialize(itemsToSend),
            Case_Identificator__c = caseExternalId
        );

        String body = JSON.serialize(platformEvent);
        httpRequest.setBody(body);

        Http http = new Http();

        try {
            HttpResponse response = http.send(httpRequest);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}