force-app/main/default/objects/Case/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Case External Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_case_items__e/External_case_items__e.object-meta.xml
<CustomObject>
    <label>External case items</label>
    <pluralLabel>External cases items</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_case_items__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Approval_Status__e/Item_Approval_Status__e.object-meta.xml
<CustomObject>
    <label>Item Approval Status</label>
    <pluralLabel>Item Approval Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Item_Approval_Status__e/fields/Item_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Item_External_Id__c</fullName>
    <label>Item External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Approval_Status__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Approval_Status__e/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <label>Case External Id</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Return Money</fullName>
            </value>
            <value>
                <fullName>Resend items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/ReturnItemsEventTests.cls
@isTest
private class ReturnItemsEventTests {
    @TestSetup
    static void createTestData() {
        new DataGenerator().createData();
    }

    @isTest
    static void testExternalCaseGettingCreated() {
        Test.startTest();
        External_case_items__e event = new External_case_items__e();
        List<Return_Item__c> returnItems = [SELECT Id, Case_External_Id__c, External_Id__c FROM Return_Item__c];
        event.Payload__c = JSON.serialize(returnItems);
        event.Case_Identificator__c = [SELECT Id, Case_External_Id__c FROM Case LIMIT 1].Case_External_Id__c;
        Database.SaveResult publishResult = EventBus.publish(event);
        Assert.areEqual(publishResult.isSuccess(), true);
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Case> cases = [SELECT Id FROM Case];
        Assert.areEqual(cases.size(), 2);
    }

    @isTest
    static void testExternalApprovalModifiesItems() {
        Test.startTest();
        Item_Approval_Status__e event = new Item_Approval_Status__e();
        Return_Item__c returnItem = [SELECT External_Id__c FROM Return_Item__c LIMIT 1];

        String returnItemExternalId = returnItem.External_Id__c;

        event.Status__c = 'Approved';
        event.Strategy__c = 'Resend items';
        event.Item_External_Id__c = returnItemExternalId;

        Database.SaveResult publishResult = EventBus.publish(event);
        Assert.areEqual(publishResult.isSuccess(), true);
        Test.getEventBus().deliver();
        Test.stopTest();
        Return_Item__c changedReturnItem = [SELECT Status__c, Strategy__c FROM Return_Item__c WHERE External_Id__c = :returnItemExternalId];
        Assert.areEqual(changedReturnItem.Status__c, 'Approved');
        Assert.areEqual(changedReturnItem.Strategy__c, 'Resend items');
    }

    class DataGenerator extends TestDataGenerator {
        public void createData() {
            Product2 firstProduct = createExternalProduct();
            Product2 secondProduct = createExternalProduct();

            Id pricebookId = Test.getStandardPricebookId();
            Pricebook2 pricebook = new Pricebook2(IsActive = true);
            pricebook.Id = pricebookId;
            update pricebook;

            PricebookEntry firstPricebookEntry = createPricebookEntry(pricebook, firstProduct, 40.0);
            PricebookEntry secondPricebookEntry = createPricebookEntry(pricebook, secondProduct, 40.0);

            Account acc = createAccount();

            Order order = createOrder(pricebook, acc);
            Case createdCase = createCaseWithExternalId();

            OrderItem firstOrderItem = createOrderItem(order, firstProduct, 14, firstPricebookEntry);
            OrderItem secondOrderItem = createOrderItem(order, secondProduct, 12, secondPricebookEntry);

            Return_Item__c firstReturnItem = createReturnItem(
                createdCase.Case_External_Id__c,
                firstOrderItem,
                10,
                firstProduct.ProductExternalId__c
            );
            Return_Item__c secondReturnItem = createReturnItem(
                createdCase.Case_External_Id__c,
                secondOrderItem,
                5,
                secondProduct.ProductExternalId__c
            );

            firstReturnItem.Case_External_Id__c = createdCase.Case_External_Id__c;
            secondReturnItem.Case_External_Id__c = createdCase.Case_External_Id__c;
            update firstReturnItem;
            update secondReturnItem;
        }
    }
}