force-app/main/default/objects/Case/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Case External Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_case_items__e/External_case_items__e.object-meta.xml
<CustomObject>
    <label>External case items</label>
    <pluralLabel>External cases items</pluralLabel>
</CustomObject>

force-app/main/default/objects/External_case_items__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Case_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_External_Id__c</fullName>
    <label>Case External Id</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <label>Product External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Returned_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Returned_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Returned Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Return Money</fullName>
            </value>
            <value>
                <fullName>Resend items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Synchronized__c.field-meta.xml
<CustomField>
    <fullName>Synchronized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synchronized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/EventExternalCaseItemsTriggerHandler.cls
public class EventExternalCaseItemsTriggerHandler extends TriggerHandler {
    protected override void afterInsert() {
        List<Return_Item__c> returnItems = new List<Return_Item__c>();
        List<Case> casesToInsert = new List<Case>();
        Map<String, Case> casesMap = new Map<String, Case>();

        for (External_case_items__e event : (List<External_case_items__e>) Trigger.new) {
            returnItems.addAll((List<Return_Item__c>) JSON.deserialize(event.Payload__c, List<Return_Item__c>.class));

            Case caseToAdd = new Case(
                Status = 'New',
                Subject = String.format('External return order of id {0}', new List<String>{ event.Case_Identificator__c }),
                Case_External_Id__c = event.Case_Identificator__c
            );

            casesToInsert.add(caseToAdd);
            casesMap.put(caseToAdd.Case_External_Id__c, caseToAdd);
        }

        insert casesToInsert;

        List<Return_Item__c> itemsToAdd = new List<Return_Item__c>();

        for (Return_Item__c item : returnItems) {
            itemsToAdd.add(
                new Return_Item__c(
                    Status__c = 'Pending',
                    Strategy__c = 'None',
                    Product__r = new Product2(ProductExternalId__c = item.Product_External_Id__c),
                    Synchronized__c = true,
                    Returned_Quantity__c = item.Returned_Quantity__c,
                    External_Id__c = item.External_Id__c,
                    Case__c = casesMap.get(item.Case_External_Id__c).Id,
                    Case_External_Id__c = item.Case_External_Id__c
                )
            );
        }

        insert itemsToAdd;

        for (Case createdCase : casesToInsert) {
            System.enqueueJob(new CaseCreatedEventQueueable(createdCase.Case_External_Id__c));
        }
    }
}