force-app/main/default/objects/Item_Approval_Status__e/Item_Approval_Status__e.object-meta.xml
<CustomObject>
    <label>Item Approval Status</label>
    <pluralLabel>Item Approval Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Item_Approval_Status__e/fields/Item_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Item_External_Id__c</fullName>
    <label>Item External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Approval_Status__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Approval_Status__e/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
                <isActive>false</isActive>
                <label>Reject</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Return Money</fullName>
            </value>
            <value>
                <fullName>Resend items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/queueable/ReturnItemSyncQueueable.cls
public class ReturnItemSyncQueueable implements Queueable, Database.AllowsCallouts {
    public Return_Item__c returnItem;

    public ReturnItemSyncQueueable(Return_Item__c returnItem) {
        this.returnItem = returnItem;
    }

    public void execute(QueueableContext context) {
        Item_Approval_Status__e event = new Item_Approval_Status__e();
        event.Item_External_Id__c = returnItem.External_Id__c;
        event.Status__c = returnItem.Status__c;
        event.Strategy__c = returnItem.Strategy__c;

        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint('callout:SynchronizeProducts/services/data/v61.0/sobjects/Item_Approval_Status__e');

        String body = JSON.serialize(event);
        httpRequest.setBody(body);

        Http http = new Http();

        try {
            HttpResponse response = http.send(httpRequest);
        } catch (Exception e) {
        }
    }
}