force-app/main/default/objects/Retry_Job__c/Retry_Job__c.object-meta.xml
<CustomObject>
    <label>Retry Job</label>
    <nameField>
        <label>Retry Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retry Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retry_Job__c/fields/Has_failed__c.field-meta.xml
<CustomField>
    <fullName>Has_failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/fields/Items_synced__c.field-meta.xml
<CustomField>
    <fullName>Items_synced__c</fullName>
    <label>Items synced</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/fields/Items_to_Sync__c.field-meta.xml
<CustomField>
    <fullName>Items_to_Sync__c</fullName>
    <label>Items to sync</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/fields/Sync_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Sync_Attempt__c</fullName>
    <label>Sync Attempt</label>
    <referenceTo>SyncAttempt__c</referenceTo>
    <relationshipLabel>Retry Jobs</relationshipLabel>
    <relationshipName>Retry_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SyncAttempt__c/SyncAttempt__c.object-meta.xml
<CustomObject>
    <label>Sync Attempt</label>
    <nameField>
        <label>SyncAttempt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sync Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SyncAttempt__c/fields/ScheduledJobId__c.field-meta.xml
<CustomField>
    <fullName>ScheduledJobId__c</fullName>
    <label>ScheduledJobId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/RetryJobTriggerHandler.cls
public with sharing class RetryJobTriggerHandler extends TriggerHandler {
    public override void afterUpdate() {
        List<Retry_Job__c> finishedJobs = new List<Retry_Job__c>();
        Set<Id> syncAttemptIds = new Set<Id>();

        for (Retry_Job__c job : (List<Retry_Job__c>) Trigger.new) {
            if (job.Items_to_Sync__c <= job.Items_synced__c) {
                finishedJobs.add(job);
                syncAttemptIds.add(job.Sync_Attempt__c);
            }
        }

        if (finishedJobs.size() <= 0) {
            return;
        }

        Set<Id> jobsToAbort = new Set<Id>();

        for (Retry_Job__c job : [
            SELECT Sync_Attempt__r.ScheduledJobId__c
            FROM Retry_Job__c
            WHERE Has_failed__c = FALSE AND Sync_Attempt__c IN :syncAttemptIds
        ]) {
            jobsToAbort.add(job.Sync_Attempt__r.ScheduledJobId__c);
        }

        AggregateResult[] groupedResult = [
            SELECT Sync_Attempt__r.ScheduledJobId__c, COUNT(Id)
            FROM Retry_Job__c
            GROUP BY Sync_Attempt__r.ScheduledJobId__c
        ];

        for (AggregateResult result : groupedResult) {
            if ((Integer) result.get('expr0') >= 3) {
                jobsToAbort.add((String) result.get('ScheduledJobId__c'));
            }
        }

        for (Id id : jobsToAbort) {
            System.abortJob(id);
        }
    }
}