force-app/main/default/objects/Account/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Discount_Requirement__c</fullName>
    <label>Discount Requirement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BooksSoldDiscountRequirements</fullName>
                <label>More than &lt;Requirement_Value&gt;  books bought</label>
            </value>
            <value>
                <fullName>OrdersPlacedDisountRequirements</fullName>
                <label>More than &lt;Requirement_Value&gt; orders placed</label>
            </value>
            <value>
                <fullName>MoneySpentDiscountRequirements</fullName>
                <label>More &lt;Requirement_Value&gt; PLN spent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Requirement_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Requirement_Value__c</fullName>
    <label>Discount Requirement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler extends TriggerHandler {
    public override void afterUpdate() {
        //TODO: Filter only those accounts which were actually changed

        List<Discount__c> allDiscounts = [SELECT Id, Discount_Requirement__c, Discount_Requirement_Value__c FROM Discount__c];
        List<AccountDiscount__c> discountsToRemove = [SELECT Id FROM AccountDiscount__c WHERE Account__c IN :Trigger.new];
        List<AccountDiscount__c> discountsToAdd = new List<AccountDiscount__c>();

        for (Account account : (List<Account>) Trigger.new) {
            for (Discount__c discount : allDiscounts) {
                DiscountRequirements requirementFunctionToUse = (DiscountRequirements) Type.forName(discount.Discount_Requirement__c)
                    .newInstance();

                if (requirementFunctionToUse.isEligibleForDiscount(account, (Double) discount.Discount_Requirement_Value__c)) {
                    discountsToAdd.add(new AccountDiscount__c(Account__c = account.Id, Discount__c = discount.Id));
                }
            }
        }

        delete discountsToRemove;
        insert discountsToAdd;
    }
}