force-app/main/default/objects/Case_Created__e/Case_Created__e.object-meta.xml
<CustomObject>
    <label>Case Created</label>
    <pluralLabel>Cases Created</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Created__e/fields/Case_Identificator__c.field-meta.xml
<CustomField>
    <fullName>Case_Identificator__c</fullName>
    <label>Case Identificator</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/queueable/CaseCreatedEventQueueable.cls
public class CaseCreatedEventQueueable implements Queueable, Database.AllowsCallouts {
    String caseId;

    public CaseCreatedEventQueueable(String caseId) {
        this.caseId = caseId;
    }

    public void execute(QueueableContext context) {
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint('callout:SynchronizeProducts/services/data/v61.0/sobjects/Case_Created__e');

        Case_Created__e event = new Case_Created__e();
        event.Case_Identificator__c = caseId;
        String body = JSON.serialize(event);
        httpRequest.setBody(body);

        Http http = new Http();

        try {
            HttpResponse response = http.send(httpRequest);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}