force-app/main/default/objects/Product_Log__c/Product_Log__c.object-meta.xml
<CustomObject>
    <label>Product Log</label>
    <nameField>
        <label>Product Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Log__c/fields/Rest_Logger__c.field-meta.xml
<CustomField>
    <fullName>Rest_Logger__c</fullName>
    <label>Rest Logger</label>
    <referenceTo>RestLogger__c</referenceTo>
    <relationshipLabel>Product Logs</relationshipLabel>
    <relationshipName>Product_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/Retry_Job__c.object-meta.xml
<CustomObject>
    <label>Retry Job</label>
    <nameField>
        <label>Retry Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retry Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retry_Job__c/fields/Items_synced__c.field-meta.xml
<CustomField>
    <fullName>Items_synced__c</fullName>
    <label>Items synced</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/fields/Items_to_Sync__c.field-meta.xml
<CustomField>
    <fullName>Items_to_Sync__c</fullName>
    <label>Items to sync</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retry_Job__c/fields/Sync_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Sync_Attempt__c</fullName>
    <label>Sync Attempt</label>
    <referenceTo>SyncAttempt__c</referenceTo>
    <relationshipLabel>Retry Jobs</relationshipLabel>
    <relationshipName>Retry_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SyncAttempt__c/SyncAttempt__c.object-meta.xml
<CustomObject>
    <label>Sync Attempt</label>
    <nameField>
        <label>SyncAttempt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sync Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SyncAttempt__c/fields/Rest_Logger__c.field-meta.xml
<CustomField>
    <fullName>Rest_Logger__c</fullName>
    <label>Rest Logger</label>
    <referenceTo>RestLogger__c</referenceTo>
    <relationshipLabel>Sync Attempts</relationshipLabel>
    <relationshipName>Sync_Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/retryier/RetryScheduler.cls
global class RetryScheduler implements Schedulable {
    public Id logId;
    public String method;
    public SyncAttempt__c syncAttempt;

    public RetryScheduler(Id logId, SyncAttempt__c syncAttempt, String method) {
        this.logId = logId;
        this.method = method;
        this.syncAttempt = syncAttempt;
    }

    global void execute(SchedulableContext context) {
        Integer itemCount = [SELECT COUNT() FROM Product_Log__c WHERE Rest_Logger__c = :logId];
        Retry_Job__c retryJob = new Retry_Job__c(Sync_Attempt__c = syncAttempt.Id, Items_to_Sync__c = itemCount, Items_synced__c = 0);
        insert retryJob;
        System.enqueueJob(new BatchedRetry(logId, retryJob, method));
    }
}