force-app/main/default/objects/Product_Log__c/Product_Log__c.object-meta.xml
<CustomObject>
    <label>Product Log</label>
    <nameField>
        <label>Product Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Log__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Logs</relationshipLabel>
    <relationshipName>Product_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Log__c/fields/ProductExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductExternalId__c</fullName>
    <label>ProductExternalId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Log__c/fields/Rest_Logger__c.field-meta.xml
<CustomField>
    <fullName>Rest_Logger__c</fullName>
    <label>Rest Logger</label>
    <referenceTo>RestLogger__c</referenceTo>
    <relationshipLabel>Product Logs</relationshipLabel>
    <relationshipName>Product_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RestLogger__c/RestLogger__c.object-meta.xml
<CustomObject>
    <label>Rest Logger</label>
    <nameField>
        <label>RestLogger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rest Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/queueable/QueueableProductSync.cls
public class QueueableProductSync implements Queueable, Database.AllowsCallouts {
    private String body;
    private String header;
    private String method;
    private String status;
    private List<Product2> products;
    private Id logId;

    public QueueableProductSync(List<Product2> products, String method) {
        this.products = products;
        this.method = method;
    }

    public void execute(QueueableContext context) {
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod(method);
        httpRequest.setEndpoint('callout:SynchronizeProducts/services/apexrest/productsync');

        String body = JSON.serialize(products);
        httpRequest.setBody(body);

        Http http = new Http();
        status = LogUtils.PENDING;
        ProductRestService.DataModel dataModel = new ProductRestService.DataModel();

        try {
            HttpResponse response = http.send(httpRequest);
            dataModel = (ProductRestService.DataModel) JSON.deserialize(response.getBody().toString(), ProductRestService.DataModel.class);
            status = dataModel.status;
        } catch (Exception e) {
            status = LogUtils.CONNECTION_ERROR;
        } finally {
            logId = logRequest();
        }
    }

    public Id logRequest() {
        List<Product_Log__c> logsToInsert = new List<Product_Log__c>();
        List<Product2> sentProducts = products;

        RestLogger__c logger = new RestLogger__c();
        logger.Header__c = header;
        logger.Method__c = method;
        logger.Status__c = status;

        insert logger;
        Set<Id> existingProducts = new Set<Id>();

        for (Product2 product : [SELECT Id FROM Product2 WHERE Id IN :sentProducts]) {
            existingProducts.add(product.Id);
        }

        for (Product2 product : sentProducts) {
            Product_Log__c productLog = new Product_Log__c(
                Rest_Logger__c = logger.Id,
                ProductExternalId__c = product.ProductExternalId__c,
                Product__c = existingProducts.contains(product.Id) ? product.Id : null
            );

            logsToInsert.add(productLog);
        }

        insert logsToInsert;

        return logger.Id;
    }
}