force-app/main/default/objects/Discount__c/fields/Discount_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Discount_Requirement__c</fullName>
    <label>Discount Requirement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BooksSoldDiscountRequirements</fullName>
                <label>More than &lt;Requirement_Value&gt;  books bought</label>
            </value>
            <value>
                <fullName>OrdersPlacedDisountRequirements</fullName>
                <label>More than &lt;Requirement_Value&gt; orders placed</label>
            </value>
            <value>
                <fullName>MoneySpentDiscountRequirements</fullName>
                <label>More &lt;Requirement_Value&gt; PLN spent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Discount_Requirement_Value__c.field-meta.xml
<CustomField>
    <fullName>Discount_Requirement_Value__c</fullName>
    <label>Discount Requirement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <label>Discount Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DiscountDataViewController.cls
public with sharing class DiscountDataViewController {
    @AuraEnabled(cacheable=true)
    public static List<Discount__c> getAllDiscounts() {
        List<Discount__c> discounts = [
            SELECT
                Id,
                Name,
                DiscountValue__c,
                toLabel(Discount_Requirement__c),
                Discount_Requirement_Value__c,
                IsActive__c,
                (SELECT Account__r.Name FROM AccountDiscounts__r)
            FROM Discount__c
        ];

        return discounts;
    }
}